### ISSUE TITLE
Investigate crash

### ISSUE THREAD

**Issue by pcarrier** [pcarrier/srv.us#13]
```
Jan 29 03:20:48 srvus srvus[517407]: panic: runtime error: invalid memory address or nil pointer dereference
Jan 29 03:20:48 srvus srvus[517407]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x40 pc=0x6763ba]
Jan 29 03:20:48 srvus srvus[517407]: goroutine 240982 [running]:
Jan 29 03:20:48 srvus srvus[517407]: main.keyMatchesAccount({0x6ed923, 0xa}, {0xc000350ed8, 0x3}, {0xc0007280a0, 0x44})
Jan 29 03:20:48 srvus srvus[517407]:         /Users/pcarrier/src/github.com/pcarrier/srv.us/backend/main.go:604 +0x23a
Jan 29 03:20:48 srvus srvus[517407]: main.(*server).serveSSHConnection(0xc000010348, 0xc000072a90, 0xc000452290)
Jan 29 03:20:48 srvus srvus[517407]:         /Users/pcarrier/src/github.com/pcarrier/srv.us/backend/main.go:383 +0x1c5
Jan 29 03:20:48 srvus srvus[517407]: created by main.(*server).serveSSH
Jan 29 03:20:48 srvus srvus[517407]:         /Users/pcarrier/src/github.com/pcarrier/srv.us/backend/main.go:361 +0x37f
Jan 29 03:20:48 srvus systemd[1]: srvus.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
```

**Comment by pcarrier** [comment]
https://github.com/pcarrier/srv.us/commit/de70c9a70fb9bc7d32fd224ebcf1a4bdba6e3ec1
