### ISSUE TITLE
ssh: connect to host srv.us port 22: Connection refused

### ISSUE THREAD

**Issue by zachadams16** [pcarrier/srv.us#14]
Me and my colleagues are seeing this error today. After srv.us has been working for months. Not sure if its something on our end

ssh: connect to host srv.us port 22: Connection refused

**Comment by pcarrier** [comment]
```
Mar 14 08:00:11 srvus srvus[943950]: panic: runtime error: invalid memory address or nil pointer dereference
Mar 14 08:00:11 srvus srvus[943950]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x673dfb]
Mar 14 08:00:11 srvus srvus[943950]: goroutine 3509048 [running]:
Mar 14 08:00:11 srvus srvus[943950]: main.(*server).serveSSHConnection(0xc0000ac330, 0xc0000a8d00, 0xc0001849b0)
Mar 14 08:00:11 srvus srvus[943950]:         /Users/pcarrier/src/srv.us/backend/main.go:379 +0x11b
Mar 14 08:00:11 srvus srvus[943950]: created by main.(*server).serveSSH
Mar 14 08:00:11 srvus srvus[943950]:         /Users/pcarrier/src/srv.us/backend/main.go:361 +0x36a
```

**Comment by pcarrier** [comment]
Thanks for the report; fixed through https://github.com/pcarrier/srv.us/commit/30adafdcc3967773d34a6cd49e50b658a9a2cf29
